### ISSUE TITLE
资产管理-》系统页面随机出现500错误

### ISSUE THREAD

**Issue by 4linuxfun** [4linuxfun/simple_ams#15]
页面会随机出现500请求错误
```
?[32mINFO?[0m:     127.0.0.1:52460 - "?[1mPOST /api/assets/system/search_total HTTP/1.0?[0m" ?[91m500 Internal Server Error?[0m
?[31mERROR?[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\ENV\fastapi\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\ENV\fastapi\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "D:\ENV\fastapi\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "D:\ENV\fastapi\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\ENV\fastapi\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "D:\ENV\fastapi\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "D:\ENV\fastapi\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "D:\ENV\fastapi\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "D:\ENV\fastapi\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "D:\ENV\fastapi\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "D:\ENV\fastapi\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "D:\ENV\fastapi\lib\site-packages\fastapi\routing.py", line 216, in app
    solved_result = await solve_dependencies(
  File "D:\ENV\fastapi\lib\site-packages\fastapi\dependencies\utils.py", line 553, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "D:\ENV\fastapi\lib\site-packages\fastapi\dependencies\utils.py", line 688, in request_body_to_args
    v_, errors_ = field.validate(value, values, loc=loc)
  File "pydantic\fields.py", line 723, in pydantic.fields.ModelField.validate
  File "pydantic\fields.py", line 906, in pydantic.fields.ModelField._validate_singleton
  File "pydantic\fields.py", line 913, in pydantic.fields.ModelField._apply_validators
  File "pydantic\class_validators.py", line 310, in pydantic.class_validators._generic_validator_basic.lambda12
  File "D:\ENV\fastapi\lib\site-packages\sqlmodel\main.py", line 581, in validate
    model = cls(**values)
  File "<string>", line 4, in __init__
  File "D:\ENV\fastapi\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "D:\ENV\fastapi\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\ENV\fastapi\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "D:\ENV\fastapi\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "<string>", line 6, in __init__
  File "D:\ENV\fastapi\lib\site-packages\sqlmodel\main.py", line 502, in __init__
    setattr(__pydantic_self__, key, value)
  File "D:\ENV\fastapi\lib\site-packages\sqlmodel\main.py", line 516, in __setattr__
    set_attribute(self, name, value)
  File "D:\ENV\fastapi\lib\site-packages\sqlalchemy\orm\attributes.py", line 2240, in set_attribute
    state.manager[key].impl.set(state, dict_, value, initiator)
AttributeError: 'NoneType' object has no attribute 'set'
```

**Comment by 4linuxfun** [comment]
点击其他页面的请求正常，然后再次点击又恢复。初步怀疑是线程安全相关问题导致的。需要进一步排查

**Comment by 4linuxfun** [comment]
此issue关闭，此项目准备作为fastapi admin基础包使用
